### ISSUE TITLE
The Brackets are still showing

### ISSUE THREAD

**Issue by Liong1976** [mgmeyers/obsidian-zotero-desktop-connector#1]
First of all, thanks a lot for making this amazing plugin.

I have an issue with the Pandoc citation. Even though I have not checked `Include Brackets` but the brackets are still showing.

![image](https://user-images.githubusercontent.com/88898230/158485818-3cdd0d40-f829-4d04-a507-813826b9d650.png)

![image](https://user-images.githubusercontent.com/88898230/158486064-5c1f07a4-f488-450b-9a4a-52563aef2345.png)

### Installer Version

0.13.31

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Theme

Shimmering Focus

**Comment by mgmeyers** [comment]
Apologies about that @Liong1976. This should be fixed now in the latest version. Let me know if you still have issues.

**Comment by Liong1976** [comment]
Thanks, @mgmeyers. It works well now!
