### ISSUE TITLE
version 1.1.3. fails to load

### ISSUE THREAD

**Issue by davidlohner** [mgmeyers/obsidian-zotero-desktop-connector#10]
Hi there,

after the update to the most recent version (1.1.3), the plugin fails to load in Obsidian (v0.14.2 on macOS 12.3).

**Comment by mgmeyers** [comment]
Thanks for the report @davidlohner. Are there any errors in the developer console when you try to enable the plugin?

<img width="254" alt="Screen Shot 2022-03-28 at 12 27 42 PM" src="https://user-images.githubusercontent.com/2694747/160472092-06566836-ea80-45d5-be5a-e8ef021aef29.png">

**Comment by davidlohner** [comment]
Does this help?

```
app.js:1 Plugin failure: obsidian-zotero-desktop-connector Error: Cannot find module 'node:buffer'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:887)
    at Function.o._resolveFilename (electron/js2c/renderer_init.js:33)
    at Module._load (internal/modules/cjs/loader.js:732)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
    at ct (app.js:1)
    at r (app.js:1)
    at anonymous (eval at <anonymous> (app.js:1), <anonymous>:76:350)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
A @ app.js:1
e.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
A @ app.js:1
e.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
A @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
```

**Comment by mgmeyers** [comment]
Ah, interesting... Hmm. What's your obsidian installer version?

<img width="777" alt="Screen Shot 2022-03-28 at 12 38 41 PM" src="https://user-images.githubusercontent.com/2694747/160473965-7432127d-dea9-4e1f-8d9a-fb1d25edfec4.png">

**Comment by davidlohner** [comment]
Uh, I'm on v0.13.14.

...just updated to v0.14.2 – now the plugin works fine again.

**Comment by mgmeyers** [comment]
Ah, strange, but glad that worked! I'll add a note to the docs.

**Comment by ShangWangNUST** [comment]
Hi there,

after the update to the most recent version (1.1.4), the plugin fails to load in Obsidian (v0.14.2 on macOS 12.3).

<img width="999" alt="CleanShot 2022-03-29 at 17 20 22@2x" src="https://user-images.githubusercontent.com/80505084/160579659-2b6b9d32-be74-409e-bd5c-4fde6352c6bb.png">

![CleanShot 2022-03-29 at 17 25 40](https://user-images.githubusercontent.com/80505084/160580087-1e044b3c-ec3b-4f8a-9a4e-0d7d9c9c7526.gif)

**Comment by davidlohner** [comment]
as above: try reinstalling Obsidian (new installer).

**Comment by ShangWangNUST** [comment]
> as above: try reinstalling Obsidian (new installer).

It works! Thank you~
