### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by sutzig** [mgmeyers/obsidian-zotero-desktop-connector#11]
I just download the new 1.1.3 ZDC main.js, manifest.json, and styles.css files to an obsidian-zotero-desktop-connector folder within the Obsidian plugins directory.  The plug in is recognized in the settings, but when I try to enable the plugin, I get the error "Failed to load obsidian-zotero-desktop-connector." I uninstall the plugin and downloaded the file again, but continue to get the same error. FWIW: this is the same process I used for the previous releases and it worked perfectly.

![image](https://user-images.githubusercontent.com/82851334/160508109-763b10ab-e175-4ed1-a79d-d5cbc61879bc.png)

![image](https://user-images.githubusercontent.com/82851334/160507959-a4243b61-c10d-4a0c-a7a7-1d1a468fff40.png)

![image](https://user-images.githubusercontent.com/82851334/160508024-43b737e5-ea18-4698-985f-19869704ae0a.png)

**Comment by mgmeyers** [comment]
Hi there @sutzig. Apologies for the confusion here. Try re-installing obsidian using the latest version. That seemed to help here: https://github.com/mgmeyers/obsidian-zotero-desktop-connector/issues/10

Let me know if that doesn't work.

**Comment by sutzig** [comment]
Thank you for your incredibly fast reply and solution. Sorry I didn't just that first. The plugin is working without issue with Obsidian 0.14.2. Thank you for your support and contribution of this fantastic plugin.
