### ISSUE TITLE
Clarification of goal and functions of this plugin

### ISSUE THREAD

**Issue by Rhydderch** [mgmeyers/obsidian-zotero-desktop-connector#2]
Hi mgmeyers!
I was looking at your github profile to see what you had been working on lately (because I was encountering a small bug with kanban and card links [#486](https://github.com/mgmeyers/obsidian-kanban/issues/486) ).
I stumbled upon this plugin that looks just amazing :) I love that you are able to trigger the search using Zotero connector to integrate citations into obsidian.

I noticed you have a feature to import notes into a document. I wonder whether your aim is to come up with similar functionalities as the [bibnotes plugin](https://github.com/stefanopagliari/bibnotes)? It would be great to have a fusion of your two plugins, but I admit I don't know how realistic or feasible this would be as the two plugins can coexist.

But perhaps, you want this plugin to be very specific in its use and do what it is currently doing: citations, bibliography, and simple note inserts in any document.

**Comment by mgmeyers** [comment]
@Rhydderch I just released a new update that also adds the ability to export data from Zotero into markdown files in Obsidian. This allows creating literature notes and exporting / formatting annotations from PDFs. I don't plan to add much more than this beyond maybe syncing notes from Obsidian to Zotero

**Comment by Rhydderch** [comment]
> beyond maybe syncing notes from Obsidian to Zotero
This would be awesome if possible! Although I guess it will only fit the workflow of some people.

For now, I use your plugin for the smooth integration with zotero. Having the zotero dialog pop-up is very neat, thank you :).
I still use bibnotes for importing annotations as it supports updating annotations but I will keep an eye out for any alternative workflows.
