### ISSUE TITLE
Fearture request: include Zotero links in notes

### ISSUE THREAD

**Issue by sutzig** [mgmeyers/obsidian-zotero-desktop-connector#20]
Would it be possible to include the Zotero file links in the Import Notes function?

As I'm sure you know, the Annotations file generated by Zotero includes a link to the location of the note in the PDF and clicking on it Obsidian takes the user directly to that spot in the document. (Side note: it appears that in Zotero v6.x, this link will only take you to the annotation location when using Zotero to open/read PDFs. If that is not the Zotero setting, the link will open the document in the selected PDF reader. I believe this is a different behavior than Zotero v5.x.)

**Comment by sutzig** [comment]
Thank you for taking the time to explain the issue. That I first read "nunchuck" is probably a pretty safe gauge of my level of familiarity, but I might have a go at it just for fun.

Once again, thank you for your contribution of this awesome plugin.

**Comment by hujie12306** [comment]
It is great to support link this!

**Comment by mgmeyers** [comment]
@sutzig & @hujie12306 I was able to figure this out. Imported notes will now include links to the annotation and the zotero item:

<img width="465" alt="Screen Shot 2022-04-08 at 11 11 34 AM" src="https://user-images.githubusercontent.com/2694747/162498486-229b6825-30f7-47d3-8ce8-1aafb8d246ad.png">

**Comment by sutzig** [comment]
This is AMAZING! Thank you so much!!

**Comment by hujie12306** [comment]
Thank you so much!!!

**Comment by MountainX** [comment]
> Imported notes will now include links to the annotation and the zotero item

Thank you for your work. Can you explain how to use this?

What I tried:

I have a PDF in Zotero with 4 annotations. Here's an example of one.

```
“Yamamoto et al. also showed that the incidence of cancer after the diagnosis of IgG4-RD is significantly higher in patients with IgG4-RD than in a sex-, age-, and observation period-matched standard population” ([Okomoto et al., 2019, p. 2](zotero://select/library/items/W9I72739)) ([pdf](zotero://open-pdf/library/items/HSTVVHYF?page=2&annotation=4HB7R3BV))
```
I can import the annotations with a custom template, but my template had lacked the link to open the PDF to the highlighted text (e.g., `zotero://open-pdf/library/items/HSTVVHYF?page=2&annotation=4HB7R3BV`). I started working on that and got it partially completed, like this:

```
[Jump to annotation](zotero://open-pdf/library/items/{{itemKey}}?page={{annot.page}}&annotation={{annot.id}})“{{annot.annotatedText | nl2br}}”
```

While working on that (which I still need to test), I came across this issue. Your solution has exactly the information I wanted to include, so I thought I'd just use it instead.

I used the command `Zotero Integration: Import notes` and selected the correct item that contains my 4 annotations. The result is:

> No notes found for selected items.

What am I missing? Thank you.
