### ISSUE TITLE
Formatting Dates

### ISSUE THREAD

**Issue by oblivia-simplex** [mgmeyers/obsidian-zotero-desktop-connector#25]
Is there currently a way to format moment dates with templates? `{{date}}` currently renders as seconds since the epoch.

**Comment by mgmeyers** [comment]
Indeed! You can use [Moment formatting](https://momentjs.com/docs/#/displaying/format/) like so: `{{data | format("YYYY-MM-DD")}}`

**Comment by oblivia-simplex** [comment]
nice! thanks!
