### ISSUE TITLE
Output {{title}} is pdf not metadata

### ISSUE THREAD

**Issue by Oblique82** [mgmeyers/obsidian-zotero-desktop-connector#26]
when I generate the output file using {{title}}.md the note is titled using the attachment (pdf) file name.

The expected behaviour would be to use the metadata of the title {{title}} which works as expected in the body of the note, just not for naming the file itself

**Comment by mgmeyers** [comment]
@Oblique82 This should be fixed now. Let me know if you run into any issues with it.
