### ISSUE TITLE
Wrong: {{tags}} is objected

### ISSUE THREAD

**Issue by hujie12306** [mgmeyers/obsidian-zotero-desktop-connector#28]
## template:
```
## {{title}}
{{tags}}
{{tag0}}
{{creators}}
### Formatted Bibliography

{{bibliography}}
```
![image](https://user-images.githubusercontent.com/61086637/162579657-f95d65f9-05f1-4b1b-ada9-15c4bd4cace1.png)

## result
![image](https://user-images.githubusercontent.com/61086637/162579654-c7c17a08-2754-487e-9cb1-d646a53d35e6.png)

**Comment by lil-i321** [comment]
Same wrong display.
And obsidian warning: 
`Error converting formatted bibliography to markdown: undefinedis not a string, or an element/document/fragment node.`

BTW,  there are two import action: 
Zotero Desktop Connector: Import #1
Zotero Desktop Connector: Import notes

Can the plugin combine the two results in one file for output? @Matthew Meyers
In my opinion, it is better to have a unified file with notes, annotations, title, abstract, author name, etc.

**Comment by mgmeyers** [comment]
Hi @hujie12306 I wrote some documentation about how to work with lists of data in templates: https://github.com/mgmeyers/obsidian-zotero-desktop-connector/blob/main/docs/Templating.md#how-do-i-format-lists-of-data

To output a list of tags, you would need to use a `for` loop:

```
{% for t in tags %}{{t.tag}}{% if not loop.last %}, {% endif %}{% endfor %}
```

I've also added some pre-formatted options like:

<img width="342" alt="Screen Shot 2022-04-13 at 6 13 20 PM" src="https://user-images.githubusercontent.com/2694747/163294708-08bad2b6-4a6a-4b7a-aeb9-924ac59bd314.png">

<img width="337" alt="Screen Shot 2022-04-13 at 6 14 15 PM" src="https://user-images.githubusercontent.com/2694747/163294796-e21c6057-e1d6-4721-b257-b77fb4846a44.png">

<img width="490" alt="Screen Shot 2022-04-13 at 6 14 35 PM" src="https://user-images.githubusercontent.com/2694747/163294815-5513c91b-f69a-44a7-9414-fee126b12a29.png">

Let me know if this helps!

**Comment by hujie12306** [comment]
![image](https://user-images.githubusercontent.com/61086637/163300816-f1b33231-21a8-41d7-b2a1-3ac6633d8860.png)
![image](https://user-images.githubusercontent.com/61086637/163300832-caa874db-dd78-44f8-8e8d-32fb92bdd97b.png)
It works. I will test more later.
Thank you so much!
