### ISSUE TITLE
Changing Citation Style?

### ISSUE THREAD

**Issue by ReaderGuy42** [mgmeyers/obsidian-zotero-desktop-connector#3]
Thank you so much for making this! I couldn't get the other citation plugin to work for me, so this is great!

However, is there a way to change the citation style that governs the in-text citations the plugin adds?

The default seems to be (Author, Year) but since I'm using MLA I only need (Author Page#).

Is there a way to change this?

Thanks!!

**Comment by brimwats** [comment]
Zotero preferences:
![image](https://user-images.githubusercontent.com/73113656/159164671-bb70e78d-2a34-4c9f-a1d5-d41d26f8f9eb.png)

**Comment by ReaderGuy42** [comment]
Hm, thanks, but I already have that set to the style I need:
![image](https://user-images.githubusercontent.com/71895400/159168808-6dfe0466-4384-4839-9652-493871dde45d.png)

Do I need to change anything else?
Thanks :)

**Comment by brimwats** [comment]
in my experience bibtex follows the zotero settings, but now I am not sure 🤔

**Comment by ReaderGuy42** [comment]
Can you try and switch to MLA (9th edition) and see if the citation importer outputs it correctly, i.e. (Author page-number)?
Because for me it's always (Author, Year, pp. page-numbers) which isn't the correct style for me.

**Comment by mgmeyers** [comment]
@ReaderGuy42 You can now select your desired style in the latest version of the plugin. Let me know if you have any issues with this

**Comment by mgmeyers** [comment]
Just to clarify, this is for `Formatted Citation` and `Formatted Bibliography`

**Comment by ReaderGuy42** [comment]
@mgmeyers Ah yes, I saw that but forgot to close this issue. Thanks for updating!!
