### ISSUE TITLE
Subset of CSL Styles Not Appearing for Import Settings

### ISSUE THREAD

**Issue by julroger2013** [mgmeyers/obsidian-zotero-desktop-connector#33]
I'm in the legal world, and so rely on some citation conventions not common in other professions. I've been trying to get the desktop connector set up using Juris-M, the legal offshoot of Zotero, and am having trouble designating the desired citation & important styles. 

The preferred CSL style is "JM Indigo Book", which closely mirrors the Bluebook citation style most often used by legal academics. But in working with the dropdown search boxes under "Citation Style" and "Bibliography Style," the Desktop Connector seems not to detect the "JM Indigo Book" style. 

Is there any way to make this option selectable? I have the JM Indigo Book style installed on both Juris-M & Zotero, so I know it's not an issue of needing to install the target style.

**Comment by mgmeyers** [comment]
Hi @julroger2013, do you know where this CSL style can be downloaded? I can add it to the list. But also, if you leave the style blank, this plugin will default to your Quick Copy style:

<img width="805" alt="Screen Shot 2022-04-13 at 9 08 15 AM" src="https://user-images.githubusercontent.com/2694747/163223513-1665c046-cf10-40d3-a014-65cde17e4b12.png">

**Comment by julroger2013** [comment]
Ahh, that makes sense! Didn't realize that they needed to be added into the Desktop Connector in addition to their presence on the user's copy of Juris-M/Zotero. 

The CSL Styles are all downloadable [at this link](https://juris-m.github.io/styles/), which is the Juris-M website, rather than the broader Zotero CSL repository.  

Thank you for making this wonderful plug-in!

**Comment by mgmeyers** [comment]
Thanks @julroger2013, I've added all the Juris-M CSL styles to the list!

**Comment by julroger2013** [comment]
No, thank you! You're beyond awesome; I'm always amazed by how much plugin developers like you contribute to the Obsidian community.
