### ISSUE TITLE
template for export filename not rendering completely

### ISSUE THREAD

**Issue by osaze-nosaze** [mgmeyers/obsidian-zotero-desktop-connector#34]
Hi, mgmeyers
Thanks for this extremely useful and promising plugin for Obsidian. I find, though, that the template for the export filename only renders partially. Forgive me if my statement is unclear: I am new to templating. What I mean is this: I have a template for the export filename thus: {{authors}} - {{date | format("YYYY")}} - {{title}}

However, the filename of the export renders without the author's name; e.g., "- 2014 - Philosophy in Pre-colonial Africa" instead of "Meyers - 2014 - Philosophy in Pre-colonial Africa".

The same template works correctly as Header 1 in the document but not in its filename. I cannot understand why. Perhaps I am missing something? 

This issue seems related to another raised by someone else regarding the template for the export filename rendering as the filename for the item's PDF. But it also seems significantly different; moreover that issue has been closed.

Thanks in advance for your help.

**Comment by mgmeyers** [comment]
Thanks for bringing this to my attention @osaze-nosaze, not all of the template data was making to the file name templates. This should be fixed now in the latest version. Let me know if you have any more issues with it.

**Comment by osaze-nosaze** [comment]
Thank you very much. Yes, I have tested with the latest version and the issue has been resolved. I appreciate your plugin, as I am sure other Obsidian+Zotero users must.
