### ISSUE TITLE
how to output property of variable

### ISSUE THREAD

**Issue by osaze-nosaze** [mgmeyers/obsidian-zotero-desktop-connector#35]
Hi, mgmeyers
I need help outputing the property of a variable. Pardon me if I am using the wrong terms. What I want to do is format the Heading 1 title of my zotero export file like this: authorlastname - year - publication title.
I am able to get author - year - publication title using this template: {{authors}} - {{date}} - {{title}}. This renders, for instance, as "M. G. Meyers - 2014 - Philosophy in Pre-colonial Africa". What I want however is: "Meyers - 2014 - Philosophy in Pre-colonial Africa", i.e., without the initials M. G.

I see in the data explorer that the author's last name is an item under the "creators" variable, as shown in the screenshot below:
![creators variable and items](https://user-images.githubusercontent.com/89715264/163283202-000ec69f-7885-404b-924b-5f748be1dfdf.png)

My challenge is how to get the plugin to output the desired last name. I have tried {{creators.0.lastName}}, {{creators.creator.lastName}}, and {{creators.creator0.lastName}}. Nothing has worked.

I would appreciate your assistance. Thanks in advance.

**Comment by mgmeyers** [comment]
Almost there @osaze-nosaze. To grab a specific item out of a list, it would look like this:

```
{{creators[0].lastName}}
```

**Comment by osaze-nosaze** [comment]
Thanks so much. I appreciate your quick response. I have followed your answer, and it's worked.
