### ISSUE TITLE
items on context dropdown list in zotero are incomplete

### ISSUE THREAD

**Issue by osaze-nosaze** [mgmeyers/obsidian-zotero-desktop-connector#36]
Hi there!
Thanks for this great plugin. It has already significantly enhanced integration between Obsidian and Zotero in my workflow. I find, however, that when I right-click on an Obsidian-Zotero synced item in Zotero and point to "Open ObsidianMD Note" or "Show Markdown File" I only get a list that seems limited to 16 Obsidian notes although I may have many more notes with the relevant Zotero itemkey. I cannot seem to find any button to scroll down to see other notes or some other means to see them.
Is this perhaps by design, or is it a bug? Or am I doing something wrong?

I could not find any thread on this issue and decided to submit it as a new one. I am sorry if I missed an already-existing thread on it.
Thanks for your help

**Comment by mgmeyers** [comment]
Hi @osaze-nosaze, I sounds like you're referring to the zotero-obsidian-citations plugin. Is that correct? If so, you may want to open an issue here, instead: https://github.com/daeh/zotero-obsidian-citations/issues

**Comment by osaze-nosaze** [comment]
No, I am referring to your plugin, the Obsidian-Zotero Desktop Connector. It is the Connector that performs the function I described, is it not? I am finding it immensely useful in my workflow and appreciate your initiative and the work you have put into it. You might wish to check to see whether you are able to reproduce the issue I described.

**Comment by mgmeyers** [comment]
I guess I'm not sure what you mean, @osaze-nosaze. Could you share screenshots? "Open ObsidianMD Note" and "Show Markdown File" are not part of this plugin.

**Comment by osaze-nosaze** [comment]
Ah!!! Please pardon my error. I just checked and found that, indeed, the plugin in question is Zotero-Obsidian Citations. Forgive that I have caused you effort and time, needlessly.

**Comment by mgmeyers** [comment]
No worries, thanks for sharing your thoughts, @osaze-nosaze!
