### ISSUE TITLE
Cache all citekeys instead of fetching them each time

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-zotero-desktop-connector#43]
Citekey autocomplete is kind of wonky. We can use a pull export to grab them all, though, we'd have to update the cache at regular intervals?

**Comment by danieltomasz** [comment]
The citations plugin probably caching its data, it has a palette command for refreshing zotero database and probably refreshing when plugin start, maybe regular update is not needed in that setup

**Comment by mgmeyers** [comment]
Implemented!
