### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by petscare** [mgmeyers/obsidian-zotero-desktop-connector#44]
Version : 
1. Zotero Desktop Connector : 2.1.7
2. Obsidian : v.0.14.6

Thanks.

**Comment by mgmeyers** [comment]
@petscare what's your obsidian installer version?

Eg:
<img width="205" alt="Screen Shot 2022-04-29 at 6 22 11 PM" src="https://user-images.githubusercontent.com/2694747/166085045-37f44cbe-1eee-4947-bf43-24bf2cf55ea6.png">

**Comment by petscare** [comment]
Installer version ? 

![image](https://user-images.githubusercontent.com/2098727/166088140-720f4a7d-1e27-4603-9e82-863f53b127bd.png)

Change to 
![image](https://user-images.githubusercontent.com/2098727/166088173-bb041db8-9fa0-4445-9c4b-1974fd846790.png)

It's working!
Sorry about my mistake!
Thans!
