### ISSUE TITLE
for some items, creators/year is not enough to disambiguate when adding annotations

### ISSUE THREAD

**Issue by erazlogo** [mgmeyers/obsidian-zotero-desktop-connector#46]
I have several letters with the same sender and recipient sent in the same year. When adding an annotation, the options all look the same:
<img width="812" alt="Screen Shot 2022-04-30 at 3 52 35 AM" src="https://user-images.githubusercontent.com/470560/166104179-08a4ae15-b141-4b63-a117-eec7a99540ff.png">

**Comment by mgmeyers** [comment]
So this is actually an issue with Zotero and not something that's fixable on my end. But there is a feature that might help here. If you click on the zotero logo, you can select "Classic View" that will give you more information:


<img width="819" alt="Screen Shot 2022-04-30 at 10 20 33 AM" src="https://user-images.githubusercontent.com/2694747/166115807-bec0e429-60ae-44ee-9cd8-a6da7e07cd3b.png">

<img width="846" alt="Screen Shot 2022-04-30 at 10 45 06 AM" src="https://user-images.githubusercontent.com/2694747/166116527-7f11c674-29e1-4f7f-91ca-fde34d5939af.png">


If you prefer this view by default, you can set it here:

<img width="703" alt="Screen Shot 2022-04-30 at 10 44 17 AM" src="https://user-images.githubusercontent.com/2694747/166116495-3ee1e384-24fe-46eb-a1ad-f67310ed35dc.png">

**Comment by erazlogo** [comment]
Oh, yes, this will work! Thank you.
