### ISSUE TITLE
BUG: Insert notes into current document not working

### ISSUE THREAD

**Issue by eleanorkonik** [mgmeyers/obsidian-zotero-desktop-connector#5]
here's my zotero:

![image](https://user-images.githubusercontent.com/75856959/159137757-6f485849-5e3d-4188-9bc0-baab9677cffe.png)

but when I try to insert my notes into the current document using the Zotero Desktop Connector, it throws an error that says "no notes found for selected items." 

I didn't see any errors in devtools. I'm on Zotero 6 and ZDC 1.0.2

**Comment by brimwats** [comment]
Same!

**Comment by davidlohner** [comment]
Same here.
Zotero 6.0.1 

Inserting citations works just fine.

**Comment by sutzig** [comment]
Just wanted to chime in to say I'm having the same issue with Zotero 6.04. I have tested both with annotations made in Zotero and annotations made with an external PDF reader.

**Comment by mgmeyers** [comment]
This should be fixed now in the latest version! Let me know if this is not the case.
