### ISSUE TITLE
 PDF annotation extraction and literature note creation

### ISSUE THREAD

**Issue by eleanorkonik** [mgmeyers/obsidian-zotero-desktop-connector#6]
> For the sake of flexibility, I'd like to support a robust templating engine of some sort for annotations and literature notes, but I also want to be mindful of non-technical users. 

The consensus was that: 

* templater is a bit much. 
* [nunjucks](https://mozilla.github.io/nunjucks/templating.html#if) is pretty user-friendly. 
* jinja is used by readwise but is python not javascript; nunjucks is the typescript alternative recommended by argentum & mgmeyers; there's also one obsidian plugin using nunjucks already. 
* mdnotes `{{ }}` style is nice but probably harder to implement. 

See also: [my request for templating on the zotero forums](https://forums.zotero.org/discussion/95239/toggle-to-auto-export-pdf-highlights-annotations#latest) & [the extract pdf annotations plugin](https://github.com/mgmeyers/obsidian-extract-pdf-annotations). 

Additionally, here's @argenos's [wishlist in Discord](https://discord.com/channels/686053708261228577/928964558721265694/952626575583621161), mostly surrounding templating options.

**Comment by mgmeyers** [comment]
So, this is basically implemented, though the documentations needs improvement, and I'm sure there will be bugs that need to be fixed. Going to close this, but let me know if you think it should remain open, @eleanorkonik!
