### ISSUE TITLE
Citation Formatting Naming Bug

### ISSUE THREAD

**Issue by brimwats** [mgmeyers/obsidian-zotero-desktop-connector#8]
I get this weird thing when setting up the Citation Formats where the plugin saves every keystroke:

![image](https://user-images.githubusercontent.com/73113656/159164508-50345969-f35d-41ac-a157-093ac57fef0a.png)

**Comment by ReaderGuy42** [comment]
I had this too, but restarting Obsidian made it go away for me.

**Comment by brimwats** [comment]
that looks right! thanks
